defaultPortal: CoinLaundryAssociation
portals:
  - name: CoinLaundryAssociation
    portalId: 19544225
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CO_fw-rzMhIaAA0AQAAA4G0DQAJYAmEAAPgAwAAAAAAAAAYYofGoCSDmhM4FKO7pDDIUxLrRpO_GvOKzwpJi2Bdip4QA-BA6TwAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAsAwAAAAAAPP4DAMAAAAAAAAwEAAAAAAAAAAAAABAAAMBCFKNImI8fUjxgiu59EhL-0Gaaa38RSgNuYTFSAFoAYAFo5oTOBXAA
        expiresAt: '2025-06-04T23:40:03.987Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiRuYTEtZjk2YS1kM2ZjLTRjZmUtODljNy1jODg0YzQwNzZmMWUQofGoCRjmhM4FKhkABeaRgoOT7lhGnTd-0owUQ3xITJWa2Kc4SgNuYTE
